### ISSUE TITLE
垃圾东西,本菇凉最讨厌你这种人了

### ISSUE THREAD

**Issue by boolean111000** [michaelliao/awesome-python-webapp#26]

**Comment by houko** [comment]
what happened.

**Comment by lycug** [comment]
https://github.com/michaelliao/awesome-python-webapp


------------------ 原始邮件 ------------------
发件人: "Peng Hu";<notifications@github.com>;
发送时间: 2018年1月26日(星期五) 上午10:46
收件人: "michaelliao/awesome-python-webapp"<awesome-python-webapp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [michaelliao/awesome-python-webapp] 垃圾东西,本菇凉最讨厌你这种人了 (#26)




what happened.
