### ISSUE TITLE
项目实战的文件呢，找不到了哦

### ISSUE THREAD

**Issue by axindeng** [michaelliao/awesome-python-webapp#30]

**Comment by axindeng** [comment]
非常抱歉，我找错路径了。已经找到了

**Comment by lycug** [comment]
https://github.com/michaelliao/awesome-python-webapp


------------------ 原始邮件 ------------------
发件人: "axindeng";<notifications@github.com>;
发送时间: 2018年1月24日(星期三) 中午12:31
收件人: "michaelliao/awesome-python-webapp"<awesome-python-webapp@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [michaelliao/awesome-python-webapp] 项目实战的文件呢，找不到了哦 (#30)




非常抱歉，我找错路径了。已经找到了
